# Generated by Django 4.0.5 on 2022-06-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_date_of_birth_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
