# Generated by Django 4.0.5 on 2022-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='attached_file',
            field=models.FileField(upload_to='', verbose_name='Attached files'),
        ),
    ]
