# Generated by Django 4.0.5 on 2022-06-10 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskassignment_notified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='assighed_at',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Assigned time'),
            preserve_default=False,
        ),
    ]
