# Generated by Django 4.0.5 on 2022-06-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connected_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connected_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
